# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/JACenterButton.xcworkspace -scheme JACenterButton -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
